### PR TITLE
Use external db replace init db

### PR DESCRIPTION
**Pull request by renyijiu**
https://github.com/supertokens/supertokens-docker-postgresql/issues/9

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
Thanks @renyijiu ! Before I merge, how have you tested this?

**Comment by renyijiu** [comment]
> Thanks @renyijiu ! Before I merge, how have you tested this?

@rishabhpoddar I have deployed in a cluster and so far no problems

**Comment by rishabhpoddar** [comment]
Have added you to the contributor's list in the supertokens-core repo.

**Comment by renyijiu** [comment]
> Have added you to the contributor's list in the supertokens-core repo.

Thanks🙏🏻

**Pull request merged**
